services:
  event-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event-service
    ports:
      - 5433:5432
    volumes:
      - event-db-data:/var/lib/postgresql/data

volumes:
  event-db-data: